
##icadcc_live_tsimis

psql.jdbc.driverClassName=org.postgresql.Driver
psql.jdbc.url=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username=icadcc
psql.jdbc.password=icadcc@123



psql.jdbc.driverClassName3=org.postgresql.Driver
psql.jdbc.url3=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username3=task
psql.jdbc.password3=task@123


psql.jdbc.driverClassName4=org.postgresql.Driver
psql.jdbc.url4=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username4=icadcomp
psql.jdbc.password4=icadcomp@123


psql.jdbc.driverClassName6=org.postgresql.Driver
psql.jdbc.url6=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username6=irparas
psql.jdbc.password6=irparas@123



psql.jdbc.driverClassName7=org.postgresql.Driver
psql.jdbc.url7=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username7=inventory
psql.jdbc.password7=inv@123


psql.jdbc.driverClassName8=org.postgresql.Driver
psql.jdbc.url8=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username8=invom
psql.jdbc.password8=invom@123


psql.jdbc.driverClassName9=org.postgresql.Driver
psql.jdbc.url9=jdbc:postgresql://10.0.4.4:5432/irrigation_ts_wts
psql.jdbc.username9=mkuser
psql.jdbc.password9=mkuser123 









psql.jdbc.driverClassName10=org.postgresql.Driver
psql.jdbc.url10=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username10=tims123
psql.jdbc.password10=tims123



psql.jdbc.driverClassName11=org.postgresql.Driver
psql.jdbc.url11=jdbc:postgresql://10.0.4.4:5432/tsimis
#icadcc@14062019
psql.jdbc.username11=stagehrms123
psql.jdbc.password11=stagehrms123


psql.jdbc.driverClassName12=org.postgresql.Driver
psql.jdbc.url12=jdbc:postgresql://10.0.4.4:5432/tsimis
#icadcc@14062019
psql.jdbc.username12=tsimis_r
psql.jdbc.password12=tsimis_r



psql.jdbc.driverClassName13=org.postgresql.Driver
psql.jdbc.url13=jdbc:postgresql://10.0.4.4:5432/irrigation_ts_wts
psql.jdbc.username13=irrigation_ts_wts
psql.jdbc.password13=irrigation_ts_wts 



#pms aws
psql.jdbc.driverClassName14=org.postgresql.Driver
psql.jdbc.url14=jdbc:postgresql://10.0.4.4:5432/irrigationpmstg
psql.jdbc.username14=irrigationpmstg
psql.jdbc.password14=IciBPDx0Rsnt4Vy





psql.jdbc.driverClassName15=org.postgresql.Driver
psql.jdbc.url15=jdbc:postgresql://10.0.4.4:5432/tsimis
psql.jdbc.username15=stagepm123
psql.jdbc.password15=stagepm123

#hrmstg AWS
psql.jdbc.driverClassName16=org.postgresql.Driver
psql.jdbc.url16=jdbc:postgresql://10.0.4.4:5432/hrmstg
psql.jdbc.username16=hrmstg
psql.jdbc.password16=HRMSTG@2050



#################



##testcggipaddress

#psql.jdbc.driverClassName=org.postgresql.Driver
#psql.jdbc.url=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username=icadcc
#psql.jdbc.password=icadcc@123


#psql.jdbc.driverClassName3=org.postgresql.Driver
#psql.jdbc.url3=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username3=task
#psql.jdbc.password3=task@123


#psql.jdbc.driverClassName4=org.postgresql.Driver
#psql.jdbc.url4=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username4=icadcomp
#psql.jdbc.password4=icadcomp@123


#psql.jdbc.driverClassName6=org.postgresql.Driver
#psql.jdbc.url6=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username6=irparas
#psql.jdbc.password6=irparas@123



#psql.jdbc.driverClassName7=org.postgresql.Driver
#psql.jdbc.url7=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username7=inventory
#psql.jdbc.password7=inv@123


#psql.jdbc.driverClassName8=org.postgresql.Driver
#psql.jdbc.url8=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username8=invom
#psql.jdbc.password8=invom@123


#psql.jdbc.driverClassName9=org.postgresql.Driver
#psql.jdbc.url9=jdbc:postgresql://10.2.28.48:9988/irrigation_ts_wts
#psql.jdbc.username9=mkuser
#psql.jdbc.password9=mkuser123 









#psql.jdbc.driverClassName10=org.postgresql.Driver
#psql.jdbc.url10=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username10=tims123
#psql.jdbc.password10=tims123



#psql.jdbc.driverClassName11=org.postgresql.Driver
#psql.jdbc.url11=jdbc:postgresql://10.2.28.48:9988/tsimis
#icadcc@14062019
#psql.jdbc.username11=stagehrms123
#psql.jdbc.password11=stagehrms123


#psql.jdbc.driverClassName12=org.postgresql.Driver
#psql.jdbc.url12=jdbc:postgresql://10.2.28.48:9988/tsimis
#icadcc@14062019
#psql.jdbc.username12=tsimis_r
#psql.jdbc.password12=tsimis_r



#psql.jdbc.driverClassName13=org.postgresql.Driver
#psql.jdbc.url13=jdbc:postgresql://10.2.28.48:9988/irrigation_ts_wts
#psql.jdbc.username13=irrigation_ts_wts
#psql.jdbc.password13=irrigation_ts_wts 



#pms aws
#psql.jdbc.driverClassName14=org.postgresql.Driver
#psql.jdbc.url14=jdbc:postgresql://10.2.28.48:9988/irrigationpmstg
#psql.jdbc.username14=irrigationpmstg
#psql.jdbc.password14=IciBPDx0Rsnt4Vy





#psql.jdbc.driverClassName15=org.postgresql.Driver
#psql.jdbc.url15=jdbc:postgresql://10.2.28.48:9988/tsimis
#psql.jdbc.username15=stagepm123
#psql.jdbc.password15=stagepm123

#hrmstg AWS
#psql.jdbc.driverClassName16=org.postgresql.Driver
#psql.jdbc.url16=jdbc:postgresql://10.2.28.48:9988/hrmstg
#psql.jdbc.username16=hrmstg
#psql.jdbc.password16=HRMSTG@2050



#################














###icadcc_cgg_knr
#psql.jdbc.driverClassName=org.postgresql.Driver
#psql.jdbc.url=jdbc:postgresql://10.3.2.90:9412/icadcc
#psql.jdbc.username=icadcc
#psql.jdbc.password=ic@dcc

#sql.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#sql.jdbc.url=jdbc:oracle:thin:@10.3.2.107:1521:CGGDB
#sql.jdbc.username=hrmspmstg	
#sql.jdbc.password=hrmspmstg
#####oldpsql.jdbc.url=jdbc:postgresql://10.2.17.139:6433/icadcc


#sql.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#sql.jdbc.url=jdbc:oracle:thin:@10.2.28.23:1521:CGGTEST
#sql.jdbc.username=hrmstg	
#sql.jdbc.password=hrmstg

#psql.jdbc.driverClassName3=org.postgresql.Driver
#psql.jdbc.url3=jdbc:postgresql://10.3.2.90:9412/icadcc
#psql.jdbc.username3=task
#psql.jdbc.password3=task@123

#psql.jdbc.driverClassName4=org.postgresql.Driver
#psql.jdbc.url4=jdbc:postgresql://10.3.2.90:9412/icadcc
#psql.jdbc.username4=icadcomp
#psql.jdbc.password4=icadcomp@123


#psql.jdbc.driverClassName6=org.postgresql.Driver
#psql.jdbc.url6=jdbc:postgresql://10.3.2.90:9412/icadcc
#psql.jdbc.username6=irparas
#psql.jdbc.password6=irparas@123

#psql.jdbc.driverClassName7=org.postgresql.Driver
#psql.jdbc.url7=jdbc:postgresql://10.3.2.90:9412/icadcc
#psql.jdbc.username7=inventory
#psql.jdbc.password7=inv@123









#icadcclocal


#psql.jdbc.driverClassName=org.postgresql.Driver
#psql.jdbc.url=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username=icadcc
#psql.jdbc.password=icadcc@123



#psql.jdbc.driverClassName3=org.postgresql.Driver
#psql.jdbc.url3=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username3=task
#psql.jdbc.password3=task@123

#psql.jdbc.driverClassName4=org.postgresql.Driver
#psql.jdbc.url4=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username4=icadcomp
#psql.jdbc.password4=icadcomp@123



#psql.jdbc.driverClassName6=org.postgresql.Driver
#psql.jdbc.url6=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username6=irparas
#psql.jdbc.password6=irparas@123


#psql.jdbc.driverClassName7=org.postgresql.Driver
#psql.jdbc.url7=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username7=inventory
#psql.jdbc.password7=inv@123



#psql.jdbc.driverClassName8=org.postgresql.Driver
#psql.jdbc.url8=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username8=invom
#psql.jdbc.password8=invom@123




#psql.jdbc.driverClassName9=org.postgresql.Driver
#psql.jdbc.url9=jdbc:postgresql://localhost/egovtanks
#icadcc@14062019
#psql.jdbc.username9=ts
#psql.jdbc.password9=ts


#psql.jdbc.driverClassName10=org.postgresql.Driver
#psql.jdbc.url10=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username10=tims123
#psql.jdbc.password10=tims123




#psql.jdbc.driverClassName11=org.postgresql.Driver
#psql.jdbc.url11=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#tsimis@22052023
#psql.jdbc.username11=stagehrms123
#psql.jdbc.password11=stagehrms123


#psql.jdbc.driverClassName12=org.postgresql.Driver
#psql.jdbc.url12=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username12=tsimis_r
#psql.jdbc.password12=tsimis_r


#psql.jdbc.driverClassName13=org.postgresql.Driver
#psql.jdbc.url13=jdbc:postgresql://localhost/egovtanks
#irrigation_ts_wts
#psql.jdbc.username13=ts
#psql.jdbc.password13=ts



#psql.jdbc.driverClassName14=org.postgresql.Driver
#psql.jdbc.url14=jdbc:postgresql://localhost/irrigationpmstg
#psql.jdbc.username14=irrigationpmstg
#psql.jdbc.password14=irrigationpmstg



#psql.jdbc.driverClassName15=org.postgresql.Driver
#psql.jdbc.url15=jdbc:postgresql://localhost/tsimis@20082025
#tsimis10082023
#psql.jdbc.username15=stagepm123
#psql.jdbc.password15=stagepm123


#psql.jdbc.driverClassName16=org.postgresql.Driver
#psql.jdbc.url16=jdbc:postgresql://localhost/hrmstg@26032024next
#psql.jdbc.username16=hrmstgnext
#psql.jdbc.password16=hrmstgnext



