errors.invalid=${getText(fieldName)} is invalid.
errors.required=  * required
errors.number=${getText(fieldName)} must be a number.
errors.range=${getText(fieldName)} is not in the range ${min} and ${max}.
error.empl.records=Error 
error.record.fetch=Error while fetching the employee details
error.update.emp=Error updating the employee information. Please check the DB Connection
error.delete.emp=Error while deleting the employee information
errors.sal.minval=*(Should be > 0)

