pdfView.(class)=in.ts.icad.leagal.util.PDFBuilder
cagpdfView.(class)=in.ts.icad.leagal.util.pdfCAGBuilder
Form20DetailPDFView.(class)=in.ts.icad.leagal.util.pdfFORM20builder
pdfirparasAbstarctview.(class)=in.ts.icad.leagal.util.pdfIRparasgistViewBuilder
cagparapdfview.(class)=in.ts.icad.leagal.util.PDFCAGpara
cagparareplypdfview.(class)=in.ts.icad.leagal.util.PDFCAGParaReply
cagparareplyallpdfview.(class)=in.ts.icad.leagal.util.PDFCAGReplyAll
cagparapacrecommondpdfview.(class)=in.ts.icad.leagal.util.PDFPACRecommondations
reservoirinfopdfabstract.(class)=in.ts.icad.leagal.util.ReservoirinfoViewBuilder

pdfReservoirAnnexure1.(class)=in.ts.icad.leagal.util.PDFReservoirAnnexure1
pdfReservoirAnnexure2.(class)=in.ts.icad.leagal.util.PDFReservoirAnnexure2
pdfEvaluateResAnnexure2.(class)=in.ts.icad.leagal.util.PDFEvaluateResAnnexure2
pdfReservoirGeninf.(class)=in.ts.icad.leagal.util.PDFReservoirGeninf
PDFReservoirInspectionInfo.(class)=in.ts.icad.leagal.util.PDFReservoirInspectionInfo

PDFHealthStatusAndRecommends.(class)=in.ts.icad.leagal.util.PDFHealthStatusAndRecommends

PDFTankGeninf.(class)=in.ts.icad.leagal.util.PDFTankGeninf

PDFReservoirSalient.(class)=in.ts.icad.leagal.util.PDFReservoirSalient

PDFTankInspectionInfo.(class)=in.ts.icad.leagal.util.PDFTankInspectionInfo

 pdfForm20Downloads.(class)=in.ts.icad.leagal.util.PDFForm20Downloads
